/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Connection.Koneksi;
import Model.Calon;
import Model.Lembaga;
import Model.TipeCalon;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Afita Afrillia
 */
public class CALONKANDIDAT extends javax.swing.JFrame {
    ArrayList<TipeCalon> listTipeCalon = new ArrayList<>();
    ArrayList<Calon> listCalon;
    Koneksi connect;
    int lembaga_id;
    /**
     * Creates new form CALONKANDIDAT
     */
    public CALONKANDIDAT() {
        initComponents();
    }
    
    public CALONKANDIDAT(int lembaga_id) {
        initComponents();
        setLocationRelativeTo(null);
        this.lembaga_id = lembaga_id;
        connect = new Koneksi();
        loadComboBoxTipeCalon();
        loadComboBoxCalon();
    }
    
    private void loadComboBoxTipeCalon(){
        cb_tipe_calon.removeAllItems();;
        try {
            String sql = "select * from tipe_calon";
            connect.ps = connect.con.prepareStatement(sql);
            connect.rs = connect.ps.executeQuery();
            while(connect.rs.next()){
                TipeCalon obj = new TipeCalon();
                obj.setTipe_calon_id(connect.rs.getInt("tipe_calon_id"));
                obj.setTipe_calon(connect.rs.getString("nama_tipe_calon"));
                listTipeCalon.add(obj);
            }
        } catch (SQLException ex) {
            System.out.println("err : "+ex.getMessage());
        }
        
        for(int i = 0; i < listTipeCalon.size(); i++){
            cb_tipe_calon.addItem(listTipeCalon.get(i).getTipe_calon());
        }
    }
    
    private void loadComboBoxCalon(){
        
        listCalon = new ArrayList<>();
        cb_calon.removeAllItems();
        try {
            String sql = "select * from calon where tipe_calon_id = "+listTipeCalon.get(cb_tipe_calon.getSelectedIndex()).getTipe_calon_id();
            System.out.println(sql);
            connect.ps = connect.con.prepareStatement(sql);
            connect.rs = connect.ps.executeQuery();
            int i=0;
            while(connect.rs.next()){
                Calon obj = new Calon();
                obj.setCalon_id(connect.rs.getInt("calon_id"));
                obj.setNama_calon(connect.rs.getString("nama_calon"));
                listCalon.add(obj);
                i++;
            }
            System.out.println(i);
        } catch (SQLException ex) {
            System.out.println("err : "+ex.getMessage());
        }
        
        for(int i = 0; i < listCalon.size(); i++){
            cb_calon.addItem(listCalon.get(i).getNama_calon());
        }
    }
    
    private void inputSuara(){
        try {
            String sql = "insert into suaracalon (calon_id,lembaga_id,jumlah_suara) "
                    + "values("+listCalon.get(cb_calon.getSelectedIndex()).getCalon_id()+","+lembaga_id+","+txSuara.getText()+")";
            System.out.println(sql);
            connect.con.createStatement().executeUpdate(sql);
            connect.con.createStatement().close();
            JOptionPane.showMessageDialog(rootPane, "SUKSES ISI SUARA");
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage(), "ERROR QUERY", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_tipe_calon = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txSuara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb_calon = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("INPUT DATA CALON");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 245, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setText("TIPE KANDIDAT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        cb_tipe_calon.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        cb_tipe_calon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KANDIDAT", "PRESIDEN & CAPRES", "DPR", "DPD", "DPRD DKI JAKARTA", "DPRD JAKARTA BARAT" }));
        cb_tipe_calon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipe_calonItemStateChanged(evt);
            }
        });
        cb_tipe_calon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipe_calonActionPerformed(evt);
            }
        });
        getContentPane().add(cb_tipe_calon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 294, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("JUMLAH SUARA ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 131, 23));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel6.setText("NAMA KANDIDAT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 131, 23));

        txSuara.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        getContentPane().add(txSuara, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 76, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        cb_calon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cb_calon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA KANDIDAT", "Joko Widodo - Maruf Amin", "Prabowo Subianto - Sandiaga Uno", "Musliha B", "Chicha Koeswoyo", "Putra Nababan", "Harun Al Rasyid", "Wanda Hamidah", "Fristin Agustinus", "Muhammad Ali Reza", "Zahara Tussoleha", "Afita Afrillia", "Vegi Syam Merkury", "Muh Sukma Saputra", "Yessy Asri" }));
        cb_calon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_calonActionPerformed(evt);
            }
        });
        getContentPane().add(cb_calon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 294, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipe_calonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipe_calonActionPerformed
      
    }//GEN-LAST:event_cb_tipe_calonActionPerformed

    private void cb_calonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_calonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_calonActionPerformed

    private void cb_tipe_calonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipe_calonItemStateChanged
        // TODO add your handling code here:
        // TODO add your handling code here:
        System.out.println(cb_tipe_calon.getSelectedIndex());
        if(cb_tipe_calon.getSelectedIndex() >= 0){
            loadComboBoxCalon();
        }
    }//GEN-LAST:event_cb_tipe_calonItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        inputSuara();
        INPUTDATA id = new INPUTDATA();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        INPUTDATA id = new INPUTDATA();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALONKANDIDAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALONKANDIDAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALONKANDIDAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALONKANDIDAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALONKANDIDAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_calon;
    private javax.swing.JComboBox<String> cb_tipe_calon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txSuara;
    // End of variables declaration//GEN-END:variables
}
