/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Connection.Koneksi;
import Model.Lembaga;
import Model.Suara;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Afita Afrillia
 */
public class INPUTDATA extends javax.swing.JFrame {

    Koneksi connect;
    ArrayList<Lembaga> listLembaga = new ArrayList<>();
    /**
     * Creates new form INPUTDATA
     */
    public INPUTDATA() {
        initComponents();
        setLocationRelativeTo(null);
        connect = new Koneksi();
        loadComboBox();
        loadTable(listLembaga.get(cb_lembaga.getSelectedIndex()).getLembagaId());
    }
    
    //buat nampilin combo box dengan daftar lembaga
    private void loadComboBox(){
        cb_lembaga.removeAllItems();;
        try {
            String sql = "select * from lembaga";
            connect.ps = connect.con.prepareStatement(sql);
            connect.rs = connect.ps.executeQuery();
            while(connect.rs.next()){
                Lembaga obj = new Lembaga();
                obj.setLembagaId(connect.rs.getInt("lembaga_id"));
                obj.setLembagaName(connect.rs.getString("lembaga_name"));
                listLembaga.add(obj);
            }
        } catch (SQLException ex) {
            System.out.println("err : "+ex.getMessage());
        }
        
        for(int i = 0; i < listLembaga.size(); i++){
            cb_lembaga.addItem(listLembaga.get(i).getLembagaName());
        }
    }
    
    private void loadTable(int lembaga_id){
        ArrayList<Suara> listSuara = new ArrayList<>();
        try {
            String sql = "select b.nama_calon, c.nama_tipe_calon, sum(jumlah_suara) as suara from lembaga a, calon b, tipe_calon c, suaracalon d\n" +
                            "where a.lembaga_id = d.lembaga_id\n" +
                            "and b.calon_id = d.calon_id \n" +
                            "and b.tipe_calon_id = c.tipe_calon_id\n" +
                            "and a.lembaga_id = "+lembaga_id+" \n" +
                            "group by b.nama_calon, c.nama_tipe_calon";
            connect.ps = connect.con.prepareStatement(sql);
            connect.rs = connect.ps.executeQuery();
            while(connect.rs.next()){
                Suara obj = new Suara();
                obj.setCalon(connect.rs.getString("nama_calon"));
                obj.setTipe_calon(connect.rs.getString("nama_tipe_calon"));
                obj.setSuara(connect.rs.getInt("suara"));
                listSuara.add(obj);
            }
        } catch (SQLException ex) {
            System.out.println("err : "+ex.getMessage());
        }
        
        String[] column = {"Nama Calon", "Tipe Calon", "Jumlah Suara"};
        String[][] row = new String [listSuara.size()][3];
        for(int i =0 ; i<listSuara.size();i++){
            row[i][0]= listSuara.get(i).getCalon();
            row[i][1]= listSuara.get(i).getTipe_calon();
            row[i][2]= String.valueOf(listSuara.get(i).getSuara());
        }
        
        DefaultTableModel model = new DefaultTableModel(row, column);
        tbl_suara.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cb_lembaga = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_suara = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("INPUT DATA CALON");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 31));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Nama Lembaga");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        cb_lembaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAMA LEMBAGA", "CHARTA POLITIKA", "INDIKATOR", "CSIS", "SMRC", "LINGKARAN SURVEI INDONESIA DENNY J.A", "INDO BAROMETER", "CYRUS NETWORK", "POPULI CENTER", "KONSEP INDONESIA" }));
        cb_lembaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lembagaActionPerformed(evt);
            }
        });
        getContentPane().add(cb_lembaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        tbl_suara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Calon", "Tipe Calon", "Jumlah Suara"
            }
        ));
        jScrollPane1.setViewportView(tbl_suara);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 680, 114));

        jButton1.setText("Masukan Suara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 60, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -230, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_lembagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lembagaActionPerformed
        // TODO add your handling code here:
        if(cb_lembaga.getSelectedIndex() >= 0){
            loadTable(listLembaga.get(cb_lembaga.getSelectedIndex()).getLembagaId());
        }
    }//GEN-LAST:event_cb_lembagaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CALONKANDIDAT calon = new CALONKANDIDAT(listLembaga.get(cb_lembaga.getSelectedIndex()).getLembagaId());
        calon.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INPUTDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INPUTDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INPUTDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INPUTDATA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INPUTDATA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_lembaga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_suara;
    // End of variables declaration//GEN-END:variables
}
